security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    api:
      pattern: ^/api
      stateless: true
      entry_point: jwt
      json_login:
        check_path: /api/signin/password
        username_path: email
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      jwt: ~ # enabled the jwt authenticator
      refresh_jwt:
        check_path: /api/token/refresh
      logout:
        path: api_token_invalidate

  access_control:
    - { path: ^/api/signin/password, roles: PUBLIC_ACCESS }
    - { path: ^/api/(signup|token/refresh), roles: PUBLIC_ACCESS }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/forgot-password, role: PUBLIC_ACCESS }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4
        time_cost: 3
        memory_cost: 10
